### ISSUE TITLE
create_chainer_model NO RESPONSE

### ISSUE THREAD

**Issue by dovanchan** [dsanno/chainer-neural-style#2]
HI:
  I had downloaded the VGG_ILSVRC_16_layers.caffemodel in the directory.
But when I run creat_chainer_model.py,It just stop in load model without any change.
Is it a bug? what should I  do for this .

**Comment by dsanno** [comment]
Are there any console messages?
If the console is showing "load VGG16 caffemodel", the program should be loading caffe model file.
It takes several minutes, and please be patient.

**Comment by dovanchan** [comment]
I have waited about 1 hours, It still no complete the loading~I had tried many times, it still no work

Stop at here:
/chainer-neural-style$ python src/create_chainer_model.py
load VGG16 caffemodel .

**Comment by dsanno** [comment]
Can you create CaffeFunction instance?
Please confirm if CaffeFunction constructor works as follows:
```
(on Python interactive shell)
>>> from chainer.links.caffe import CaffeFunction
>>> ref = CaffeFunction('VGG_ILSVRC_16_layers.caffemodel')
```

If it doesn't work, I think Chainer or protobuf package may not be correctly installed or caffe model file may be corrupted.

**Comment by dovanchan** [comment]
>>> from chainer.links.caffe import CaffeFunction
>>> ref = CaffeFunction('VGG_ILSVRC_16_layers.caffemodel')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cu_00095/.local/lib/python2.7/site-packages/chainer/links/caffe/caffe_function.py", line 133, in __init__
    with open(model_path, 'rb') as model_file:
IOError: [Errno 2] No such file or directory: 'VGG_ILSVRC_16_layers.caffemodel'


Can you tell me where is the correct path for the VGG_ILSVRC_16_layers.caffemodel?  
I had tried to put it in /chainer-neural-style  or . /chainer-neural-style/src 
But it still  IOError: [Errno 2] No such file or directory: 'VGG_ILSVRC_16_layers.caffemodel'

**Comment by dsanno** [comment]
The correct path for VGG_ILSVRC_16_layers.caffemodel is "chainer-neural-style".
In more detail

1. Put VGG_ILSVRC_16_layers.caffemodel into chainer-neural-style directory.
2. Move to chainer-neural-style directory
3. Run Python and create CaffeFunction instance.

You can use `os.path.exists` to check whether the file exists or not.

**Comment by dovanchan** [comment]
cu_00095@gtx1080:~/chainer-neural-style$ ls
LICENSE  README.md  src   VGG_ILSVRC_16_layers.caffemodel
cu_00095@gtx1080:~/chainer-neural-style$ python src/create_chainer_model.py
load VGG16 caffemodel

cu_00095@gtx1080:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from chainer.links.caffe import CaffeFunction
>>> ref = CaffeFunction('VGG_ILSVRC_16_layers.caffemodel')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cu_00095/.local/lib/python2.7/site-packages/chainer/links/caffe/caffe_function.py", line 133, in __init__
    with open(model_path, 'rb') as model_file:
IOError: [Errno 2] No such file or directory: 'VGG_ILSVRC_16_layers.caffemodel'


I have done these, But it always stop at here 
I had tried many times, it still no work

**Comment by dovanchan** [comment]
The VGG_ILSVRC_16_layers.caffemodel has exist in the chainer-neural-style,I have checked many times;
But It still have a error for No such file.~ Is it a bug need to be fixed?

just stop at load model~

**Comment by dsanno** [comment]
Did you check VGG_ILSVRC_16_layers.caffemodel exists **on Python shell** ?
For example, do these commands work?

```
>>> import os
>>> os.getcwd()
'/path/to/current/working/directory'
>>> os.path.exists('VGG_ILSVRC_16_layers.caffemodel')
True
>>> f = open('VGG_ILSVRC_16_layers.caffemodel', 'rb')
>>> f.close()
```

**Comment by dovanchan** [comment]
>> import os
>>> os.getcwd()
'/Users/DOVAN/deeprely/chainer-neural-style'
>>> os.path.exists('VGG_ILSVRC_16_layers.caffemodel')
True
>>>  f = open('VGG_ILSVRC_16_layers.caffemodel', 'rb')
>>> f.close
<built-in method close of file object at 0x10f007300>


I have tried,It exicted,but still can not load model successful~ I think you can try once~

**Comment by dovanchan** [comment]
I have put the file "VGG_ILSVRC_16_layers.caffemodel" under '/chainer-neural-style',
But run os.path.exists('VGG_ILSVRC_16_layers.caffemodel') .  failed....
What should I do to let the python findout this model~
